<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All notifications have been deleted.' => 'Todas las notificaciones han sido eliminadas.',
    'All notifications have been marked as read.' => 'Todas las notificaciones han sido marcadas como leidas.',
    'Delete all' => 'Eliminar todas',
    'Mark all as read' => 'Marcar todas como leidas',
    'Mark as read' => 'Marcar como leida',
    'Notifications' => 'Notificaciones',
    'Read' => 'Leer',
    'There are no notifications to show' => 'No hay notificaciones para mostrar',
    'View all' => 'Ver todas',
    'a moment' => 'un momento',
    'ago' => 'atrás',
    '{n, plural, one{one day} other{# days}}' => '{n, plural, one{un dia} other{# dias}}',
    '{n, plural, one{one hour} other{# hours}}' => '{n, plural, one{una hora} other{# horas}}',
    '{n, plural, one{one minute} other{# minutes}}' => '{n, plural, one{un minuto} other{# minutos}}',
    '{n, plural, one{one month} other{# months}}' => '{n, plural, one{un mes} other{# meses}}',
    '{n, plural, one{one second} other{# seconds}}' => '{n, plural, one{un segundo} other{# segundos}}',
    '{n, plural, one{one week} other{# weeks}}' => '{n, plural, one{una semana} other{# semanas}}',
    '{n, plural, one{one year} other{# years}}' => '{n, plural, one{un año} other{# años}}',
];
