<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All notifications have been deleted.' => 'Alle Benachrichtigungen wurden gelöscht.',
    'All notifications have been marked as read.' => 'Alle Benachrichtigungen wurden als gelesen markiert.',
    'Delete all' => 'Alle löschen',
    'Mark all as read' => 'Alle als gelesen markieren',
    'Mark as read' => 'Als gelesen markieren',
    'Notifications' => 'Benachrichtigungen',
    'Read' => 'Lesen',
    'There are no notifications to show' => 'Es sind keine Benachrichtigungen zu zeigen',
    'View all' => 'Alle ansehen',
    'a moment' => 'ein Moment',
    'ago' => 'vor',
    '{n, plural, one{one day} other{# days}}' => '{n, plural, one{ein Tag} other{# Tage}}',
    '{n, plural, one{one hour} other{# hours}}' => '{n, plural, one{eine Stunde} other{# Stunden}}',
    '{n, plural, one{one minute} other{# minutes}}' => '{n, plural, one{eine Minute} other{# Minuten}}',
    '{n, plural, one{one month} other{# months}}' => '{n, plural, one{ein Monat} other{# Monate}}',
    '{n, plural, one{one second} other{# seconds}}' => '{n, plural, one{eine Sekunde} other{# Sekunden}}',
    '{n, plural, one{one week} other{# weeks}}' => '{n, plural, one{eine Woche} other{# Wochen}}',
    '{n, plural, one{one year} other{# years}}' => '{n, plural, one{ein Jahr} other{# Jahre}}',
];
