<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All notifications have been deleted.' => 'Tutte le notifiche sono state cancellate.',
    'All notifications have been marked as read.' => 'Tutte le notifiche sono state segnate come lette.',
    'Delete all' => 'Cancella tutto',
    'Mark all as read' => 'Segna tutto come letto',
    'Mark as read' => 'Segna come letto',
    'Notifications' => 'Notifiche',
    'Read' => 'Leggi',
    'There are no notifications to show' => 'Nessuna notifica da mostrare',
    'View all' => 'Vedi tutto',
    'a moment' => 'un momento',
    'ago' => 'altro',
    '{n, plural, one{one day} other{# days}}' => '{n, plural, one{un giorno} other{# giorni}}',
    '{n, plural, one{one hour} other{# hours}}' => '{n, plural, one{un ora} other{# ore}}',
    '{n, plural, one{one minute} other{# minutes}}' => '{n, plural, one{un minuto} other{# minuti}}',
    '{n, plural, one{one month} other{# months}}' => '{n, plural, one{un mese} other{# mesi}}',
    '{n, plural, one{one second} other{# seconds}}' => '{n, plural, one{un secondo} other{# secondi}}',
    '{n, plural, one{one week} other{# weeks}}' => '{n, plural, one{una settimana} other{# settimane}}',
    '{n, plural, one{one year} other{# years}}' => '{n, plural, one{un anno} other{# anni}}',
];
